[app]
app_vm ansible_host=192.168.56.21 ansible_user=vagrant ansible_private_key_file=.vagrant/machines/app/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[db]
db_vm ansible_host=192.168.56.22 ansible_user=vagrant ansible_private_key_file=.vagrant/machines/db/virtualbox/private_key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
